# models.py — Generated by VIA

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class ItemCreate(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    content: Optional[str] = Field(None, max_length=5000)


class ItemResponse(BaseModel):
    id: str
    title: str
    content: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True
