# services.py — Generated by VIA

import uuid


class ItemService:

    @staticmethod
    async def create(item) -> dict:
        return {
            "id":      str(uuid.uuid4()),
            "title":   item.title,
            "content": item.content,
            "message": "Item created successfully"
        }

    @staticmethod
    async def get_by_id(item_id: str) -> dict:
        return {
            "id":      item_id,
            "message": "Item retrieved successfully"
        }
